name: UltraGlitchProtection
author: manguvana
description: "Checks for oversized stacks, when an inventory is opened(chests, furnaces, player inventory, etc.)"
main: eu.ultragaming.UltraGlitchProtection.MainProtection
version: 1.0.2